django/polls_com/polls/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('polls.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<poll_id>\d+)/$', 'detail', name='detail'),
    url(r'^(?P<poll_id>\d+)/results/$', 'results', name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'vote', name='vote'),
    url(r'^most-voted/$', 'most_voted', name='most_voted'),
    url(r'^ranking/$', 'ranking', name='ranking'),
    url(r'^poll-create/$', 'poll_create', name='poll_create'),
    url(r'^(?P<poll_id>\d+)/edit-poll/$', 'edit_poll', name='edit_poll'),
)

django/polls_com/polls_com/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^polls/', include('polls.urls', namespace='polls')),
	url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

django/polls_com/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.db.models import Sum


class Poll(models.Model):
    question = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('date published', default=timezone.now())

    class Meta:
        permissions = (
            ('can_vote', ('puede votar')),
            ('can_create', ('puede crear')),
            ('can_edit', ('puede editar')),
        )

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __unicode__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        order_with_respect_to = 'poll'

    def porcentual(self):
        result = 0
        total_votes = self.poll.choice_set.all().aggregate(total=Sum('votes'))['total']
        if total_votes:
            result = ((self.votes + 0.0) / total_votes) * 100
        return result

    def __unicode__(self):
        return self.choice

django/polls_com/polls/forms.py
# Forms for bootstrap.
from django import forms
from polls.models import Choice, Poll
from django.forms.models import inlineformset_factory
from django.forms.formsets import BaseFormSet


class VoteForm(forms.Form):
    choice = forms.ModelChoiceField(queryset=Choice.objects.all(),
        widget=forms.RadioSelect(),
        empty_label=None,
        label='',)

    def __init__(self, *args, **kwargs):
        poll = kwargs.pop('poll')
        super(VoteForm, self).__init__(*args, **kwargs)
        self.fields['choice'].queryset = poll.choice_set.all()


ChoiceFormSet = inlineformset_factory(Poll,
    Choice,
    can_delete=False,
    extra=3,
    exclude=('votes',),
    can_order=True,
    )


class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        exclude = ('pub_date',)


class EditPollForm(forms.Form):
    question = forms.CharField(max_length=200, label="Titulo de encuesta")

django/polls_com/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from polls.models import Poll, Choice
from django.db.models import Sum
from django.views.generic import FormView, ListView, DetailView, ArchiveIndexView
from forms import VoteForm, PollForm, ChoiceFormSet, EditPollForm
from django.template import RequestContext
from django.forms.models import inlineformset_factory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def poll_create(request):
    if request.POST:
        form = PollForm(request.POST)
        formset = ChoiceFormSet(request.POST, instance=Poll())
        if form.is_valid():
            poll = form.save(commit=False)
            formset.instance = poll
            if formset.is_valid():
                if formset.save(commit=False) == []:
                    message = "Se debe colocal al menos una opcion!"
                    return render_to_response("polls/poll-create.html", {
                        "form": form,
                        "formset": formset,
                        "message": message,
                    }, context_instance=RequestContext(request))
                poll.save()
                formset.save()
                order_list = []
                for choice_form in formset.ordered_forms:
                    c = choice_form.save(commit=False)
                    order_list.append(c.id)
                poll.set_choice_order(order_list)
                return render(request, 'polls/success.html')
    else:
        formset = ChoiceFormSet(instance=Poll())
        form = PollForm()
    return render_to_response("polls/poll-create.html", {
        "form": form,
        "formset": formset,
    }, context_instance=RequestContext(request))


def edit_poll(request, poll_id):
    FormSet = inlineformset_factory(Poll,
            Choice,
            can_delete=True,
            extra=1,
            can_order=True,
            exclude=('votes',),)
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.POST:
        form = EditPollForm(request.POST)
        formset = FormSet(request.POST, instance=poll)
        if form.is_valid() and form.has_changed():
            poll.question = form.cleaned_data['question']
            poll.save()
        if formset.is_valid():
            formset.instance = poll
            formset.save()
            order_list = []
            for choice_form in formset.ordered_forms:
                order_list.append(choice_form.save(commit=False).id)
            poll.set_choice_order(order_list)
            return render(request, 'polls/success.html')
    else:
        form = EditPollForm()
        form.fields['question'].initial = poll.question
        formset = FormSet(instance=poll)
    return render_to_response("polls/edit-poll.html", {
        "poll": poll,
        "form": form,
        "formset": formset,
    }, context_instance=RequestContext(request))


def index(request, page=None):
    polls = Poll.objects.all().order_by('-pub_date')
    paginator = Paginator(polls, 2)

    page = request.GET.get('page')
    try:
        poll_list = paginator.page(page)
    except PageNotAnInteger:
        poll_list = paginator.page(1)
    except EmptyPage:
        poll_list = paginator.page(paginator.num_pages)

    return render_to_response('polls/index.html', {"poll_list": poll_list, 'request': request})


# index = ArchiveIndexView.as_view(
#     date_field='pub_date',
#     paginate_by=10,
#     allow_empty=True,
#     queryset=Paginator(Poll.objects.all().order_by('-pub_date'), 10),
#     template_name='polls/index.html',
# )

# class IndexView(ArchiveIndexView):
#     date_field = 'pub_date'
#     paginate_by = 10
#     allow_empty = True
#     queryset = Poll.objects.all().order_by('-pub_date')
#     template_name = 'polls/index.html'

#     def get_context_data(self, **kwargs):
#         context = super(IndexView, self).get_context_data(**kwargs)
#         context['latest'] = Paginator(context['latest'], 10).page(1)
#         return context
#         # if 'page' in self.kwargs:
#         #     context['latest'] = Paginator(context['latest'])
#         # else:


# index = IndexView.as_view()


class DetailViews(DetailView):
    model = Poll
    pk_url_kwarg = 'poll_id'
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailViews, self).get_context_data(**kwargs)
        poll = get_object_or_404(Poll, pk=self.kwargs['poll_id'])
        context['form'] = VoteForm(poll=poll)
        return context

detail = DetailViews.as_view()


class VoteView(FormView):
    form_class = VoteForm
    http_method_names = ['post']

    def get_form(self, form_class):
        self.poll = get_object_or_404(Poll, pk=self.kwargs['poll_id'])
        return VoteForm(self.request.POST, poll=self.poll)

    def form_valid(self, form):
        choice = form.cleaned_data['choice']
        choice.votes += 1
        choice.save()
        return redirect('polls:results', poll_id=self.poll.pk)

    def form_invalid(self, form):
        return render(self.request, 'polls/detail.html', {'poll': self.poll, 'form': form})

vote = VoteView.as_view()


class ResultView(DetailView):
    model = Poll
    pk_url_kwarg = 'poll_id'
    template_name = 'polls/result.html'

    def get_context_data(self, **kwargs):
        context = super(ResultView, self).get_context_data(**kwargs)
        poll = get_object_or_404(Poll, pk=self.kwargs['poll_id'])
        context['poll'] = poll
        return context

results = ResultView.as_view()


class RankingView(ListView):
    template_name = 'polls/ranking.html'
    queryset = Poll.objects.all()

    def get_context_data(self, **kwargs):
        context = super(RankingView, self).get_context_data(**kwargs)
        polls = Poll.objects.annotate(votes=Sum('choice__votes')).order_by('-votes')
        context['poll_list'] = polls
        return context

ranking = RankingView.as_view()


class MostVotedView(RankingView):
    template_name = 'polls/most-voted.html'

most_voted = MostVotedView.as_view()

django/polls_com/polls/templates/polls/base.html
<!DOCTYPE html>
{% load url from future %}
{% load bootstrap_toolkit %}
<html lang="es">
<head>
	{% bootstrap_stylesheet_tag %}
	<title>
	{% block title %}
	{% endblock %}
	</title>
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
            padding-left: 25px;
        }
        footer {
            height: 5px;
        }
    </style>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    {% bootstrap_javascript_tag %}
    {% block extra_head %}{% endblock %}
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{% url 'polls:index' %}">Encuestas</a>
            <ul class="nav">
                <li><a href="{% url 'polls:index' %}" class="">Inicio</a></li>
                <li><a href="#">Perfil</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Acciones<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'polls:poll_create' %}">Crear encuesta</a></li>
                        <li><a href="{% url 'polls:index' %}">Votar</a></li>
                        {% comment %}<li><a href="{% url 'polls:edit_poll' %}">Modificar encuesta</a></li> {% endcomment %}
                        <li><a href="#">Buscar</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'polls:most_voted' %}">Mas votada</a></li>
                <li><a href="{% url 'polls:ranking' %}">Ranking</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="mini-layout-body">
    <div class="container">
    {% block message %}
        {% if message %}
            <div class="alert alert-block">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>Error!</h4>
                {{ message }}
            </div>
            {% endif %}
    {% endblock %}

    {% block title_content %}
    {% endblock %}
        <div class="hero-unit">
        	{% block body %}
        		<p>
        			Empty Block
        		</p>
        	{% endblock %}
        </div>
    </div>
</div>
{% block footer %}
<footer class="navbar navbar-fixed-bottom modal-footer">
    <p>© Company 2013</p>
</footer>
{% endblock %}
</body>
</html>

django/polls_com/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load bootstrap_toolkit %}

{% block title %}Votar!{% endblock %}
{% bootstrap_stylesheet_tag %}
{% block body %}
	<h2>{{ poll.question }}</h2>
	<form action="{% url 'polls:vote' poll_id=poll.id %}"
	      method="post" class="uniForm">
	    {% csrf_token %}
	    {% include "bootstrap_toolkit/form.html" %}
	    <input type="submit" value="Votar" class="btn btn-primary">
	</form>

	<a href="{% url 'polls:index' %}">Volver</a>
{% endblock %}

django/polls_com/polls/templates/polls/edit-poll.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title %}Editar encuesta{% endblock %}

{% block extra_head %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>

<script type="text/javascript" src="{% static 'js/jquery.formset.min.js' %}"></script>

<script type="text/javascript">
    $(function() {
        $('#table tbody tr').formset({
            // For inline formsets, be sure to set the prefix, as the default prefix
            // ('form') isn't correct.
            // Django appears to generate the prefix from the lowercase plural
            // name of the related model, with camel-case converted to underscores.
            prefix: '{{ formset.prefix }}'
        })
    })
</script>
 <script>
    $(function() {
        $( "#sortable" ).sortable({
            stop: function(ui, event){
                $(".tr_sortable").each(function() {
                    var order = $(this).index();
                if ($("#id_choice_set-" + order + "-choice").val() != "") {
                    var id = '#id_choice_set-' + order + '-ORDER';
                    $(id).val(parseInt($('#choice_set-' + order).index()) + 1);
                }
            });
            }
        });
    });
</script>
<style type="text/css">
    .delete-row {
        margin-left:50px;
    }
    .controls {
    	float: left;
    }
    label[for$="ORDER"], input[id$="ORDER"], label[for$="choice"], label[for$="question"], .checkbox {
        display: none;
    }
</style>
{% endblock %}

{% block body %}

<form method="post" action="{% url 'polls:edit_poll' poll_id=poll.id %}" class="uniForm">
    <fieldset>
        {% csrf_token %}
        <strong>Titulo de encuesta:</strong>
        {% include "bootstrap_toolkit/form.html" %}
        <table id="table" class="table table-hover">
            <thead>
                <tr><th>Opciones:</th></tr>
            </thead>
            <tbody id="sortable">
                {% for form in formset.forms %}
                    <tr id="{{ form.prefix }}" class="tr_sortable">
                        <td>{% include "bootstrap_toolkit/form.html" %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {{ formset.management_form }}
        <input type="submit" value="Submit" class="btn"/>
    </fieldset>
</form>
{% endblock %}

django/polls_com/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load bootstrap_toolkit %}
{% load bootstrap_pagination %}

{% block title %} Lo último en encuestas! {% endblock %}
{% block extra_head %}
<style type="text/css">
.poll {
    padding-right: 15px;
}
.polls {
    height: 100%;
}
</style>
{% endblock %}
{% block title_content %}
    <h1>Encuestas disponibles:</h1>
{% endblock %}
{% block body %}
{% if poll_list %}
    <table class="polls">
        <tbody>
            {% for poll in poll_list %}
                <tr>
                    <td><i class="icon-play"></i></td>
                    <td>
                    <a class="poll" href= "{% url 'polls:detail' poll_id=poll.id %}" >{{ poll.question }}</a>
                    </td>
                    <td>
                    <a href= "{% url 'polls:edit_poll' poll_id=poll.id %}" class="btn btn-info btn-small">Editar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="pagination">
        {% if poll_list.has_previous %}
        <ul>
            <li class="active"><a href="?page={{ poll_list.previous_page_number }}">Anterior</a></li>
        </ul>
        {% endif %}
        <ul>
            <li class="disabled"><a href="#">&laquo;</a></li>
            <li class="active"><a href="#">{{ poll_list.number }}</a></li>
        </ul>
        {% if poll_list.has_next %}
        <ul>
            <li class="disabled"><a href="#">&laquo;</a></li>
            <li class="active"><a href="?page={{ poll_list.next_page_number }}">Siguente</a></li>
        </ul>
        {% endif %}
    </div>
{% else %}
    <p>No hay encuestas disponibles para mostrar. Podes empezar creando una haciendo clic <a href="{% url 'polls:poll_create' %}">aca!</a></p>
{% endif %}
{% endblock %}

django/polls_com/polls/templates/polls/most-voted.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load bootstrap_toolkit %}
{% load poll_tags %}

{% block title %}Mas votada!{% endblock %}
{% bootstrap_stylesheet_tag %}
{% block title_content %}
	<h2> {{ poll_list.0.question }}</h2>
{% endblock %}
{% block body %}
    {% if poll_list != None %}
        <ul>
        {% for choice in poll_list.0.choice_set.all %}
            <li>{{ choice.choice }} <br>Votos: {{ choice.votes }}
                {% porcentual_tag choice %}
             </li>
        {% endfor %}
        </ul>
	{% else %}
        <p>No hay encuestas para mostrar.</p>
	{% endif %}
{% endblock %}

django/polls_com/polls/templates/polls/poll-create.html
{% extends "polls/edit-poll.html" %}
{% load url from future %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title %}Crear encuesta{% endblock %}
{% block body %}
<form method="post" action="{% url 'polls:poll_create' %}" class="uniForm">
	 <fieldset>
		<legend><h3>Crear Encuesta</h3></legend>
	{% csrf_token %}
    <strong>Titulo de encuesta:</strong>
    {% include "bootstrap_toolkit/form.html" %}
    <table id="table" class="table table-hover">
        <thead>
            <tr><th>Opciones:</th></tr>
        </thead>
        <tbody id="sortable">
            {% for form in formset.forms %}
            <tr id="{{ form.prefix }}" class="tr_sortable">
                <td>{% include "bootstrap_toolkit/form.html" %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ formset.management_form }}
    <input type="submit" value="Submit" class="btn"/>
</fieldset>
</form>
{% endblock %}

django/polls_com/polls/templates/polls/ranking.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load bootstrap_toolkit %}

{% block title %}Mas votada!{% endblock %}
{% block extra_head %}
<style type="text/css">
    .table {
        width: 80%;
    }
</style>
{% endblock %}
{% bootstrap_stylesheet_tag %}
{% block title_content %}
<h1>Ranking de encuestas</h1>
{% endblock %}
{% block body %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Pregunta</th>
                <th>Votos</th>
                <th>Creado</th>
            </tr>
        </thead>
        <tbody>
        {% for poll in poll_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ poll.question }}</td>
                <td>{{ poll.votes }}</td>
                <td>{{ poll.pub_date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

django/polls_com/polls/templates/polls/result.html
{% extends "polls/base.html" %}
{% load url from future %}
{% load poll_tags %}
{% block title %}Gracias por votar!{% endblock %}

{% block body %}
	<p><h3>Gracias por participar en la encuesta: </h3><strong>{{ poll }}</strong></p>
	<p>Cantidad de votos:</p>
	<ul>
        {% for choice in poll.choice_set.all %}
            <li style="padding-bottom:8px">{{ choice.choice }} <br>
            	<strong>votos: </strong>{{ choice.votes }}
                {% porcentual_tag choice %}
            </li>
        {% endfor %}
        </ul>
	</ul>

	<a href="{% url 'polls:index' %}"> Elegir otra encuesta</a>
{% endblock %}

django/polls_com/polls/templates/polls/success.html
{% extends "polls/base.html" %}
{% load url from future %}

{% block title %}Encuesta creada{% endblock %}
{% block body %}
	<h2>
		<p>Muchas gracias por crear una encuesta!</p>
	</h2>
	<p>Seguila y mira cuanto éxito tiene!</p>
{% endblock %}